# Generated by Django 3.2.23 on 2023-12-10 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextDocument',
        ),
    ]
