# Generated by Django 3.2.23 on 2023-12-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_document_document_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_id',
        ),
    ]
