# Generated by Django 3.2.23 on 2023-12-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_textdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdocument',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
