# Generated by Django 3.2.23 on 2023-12-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
